# ==========================================================
# nslgo's mkdocs documentation
# ----------------------------------------------------------
# 
# See: 
# 
#   - mkdocs
#     https://www.mkdocs.org/
# 
# ----------------------------------------------------------

# Site name
site_name: nslgo Documentation

# Theme
theme: readthedocs
extra_css: [extra.css]

# ==========================================================
# ==========================================================

# fin.
